-- Use native Catppuccin from Neovim core (v0.12+)
vim.g.catppuccin_flavour = "macchiato"

local palettes = {
	macchiato = { -- Gruvbox like
		rosewater = "#ea6962",
		flamingo = "#ea6962",
		red = "#ea6962",
		maroon = "#ea6962",
		pink = "#d3869b",
		mauve = "#d3869b",
		peach = "#e78a4e",
		yellow = "#d8a657",
		green = "#a9b665",
		teal = "#89b482",
		sky = "#89b482",
		sapphire = "#89b482",
		blue = "#7daea3",
		lavender = "#7daea3",
		text = "#ebdbb2",
		subtext1 = "#d5c4a1",
		subtext0 = "#bdae93",
		subtext2 = "#d5c4a1",
		overlay2 = "#a89984",
		overlay1 = "#928374",
		overlay0 = "#595959",
		surface2 = "#4d4d4d",
		surface1 = "#404040",
		surface0 = "#292929",
		base = "#1d2021",
		mantle = "#191b1c",
		crust = "#141617",
	},
}

local function apply_custom_highlights()
	local flavor = vim.g.catppuccin_flavour or "macchiato"
	local colors = palettes[flavor] or palettes.macchiato

	local transparent_groups = {
		"Normal",
		"NormalNC",
		"LineNr",
		"Folded",
		"SignColumn",
		"EndOfBuffer",
		"NormalFloat",
		"FloatBorder",
		"VertSplit",
		"WinSeparator",
		"StatusLine",
		"StatusLineNC",
	}
	for _, group in ipairs(transparent_groups) do
		vim.api.nvim_set_hl(0, group, { bg = "NONE", ctermbg = "NONE" })
	end

	local highlights = {
		CmpItemMenu = { fg = colors.surface2 },
		CursorLineNr = { fg = colors.text },
		FloatBorder = { bg = "NONE", fg = colors.surface0 }, -- Adjusted for transparency
		GitSignsChange = { fg = colors.peach },
		LineNr = { fg = colors.overlay0 },
		LspInfoBorder = { link = "FloatBorder" },
		NeoTreeDirectoryIcon = { fg = colors.subtext1 },
		NeoTreeDirectoryName = { fg = colors.subtext1 },
		NeoTreeFloatBorder = { link = "TelescopeResultsBorder" },
		NeoTreeGitConflict = { fg = colors.red },
		NeoTreeGitDeleted = { fg = colors.red },
		NeoTreeGitIgnored = { fg = colors.overlay0 },
		NeoTreeGitModified = { fg = colors.peach },
		NeoTreeGitStaged = { fg = colors.green },
		NeoTreeGitUnstaged = { fg = colors.red },
		NeoTreeGitUntracked = { fg = colors.green },
		NeoTreeIndent = { fg = colors.surface1 },
		NeoTreeNormal = { bg = colors.mantle },
		NeoTreeNormalNC = { bg = colors.mantle },
		NeoTreeRootName = { fg = colors.subtext1, bold = true },
		NeoTreeTabActive = { fg = colors.text, bg = colors.mantle },
		NeoTreeTabInactive = { fg = colors.surface2, bg = colors.crust },
		NeoTreeTabSeparatorActive = { fg = colors.mantle, bg = colors.mantle },
		NeoTreeTabSeparatorInactive = { fg = colors.crust, bg = colors.crust },
		NeoTreeWinSeparator = { fg = colors.base, bg = colors.base },
		NormalFloat = { bg = "NONE" }, -- Adjusted for transparency
		Pmenu = { bg = colors.mantle },
		PmenuSel = { bg = colors.surface0 },
		TelescopePreviewBorder = { bg = colors.crust, fg = colors.crust },
		TelescopePreviewNormal = { bg = colors.crust },
		TelescopePreviewTitle = { fg = colors.crust, bg = colors.crust },
		TelescopePromptBorder = { bg = colors.surface0, fg = colors.surface0 },
		TelescopePromptCounter = { fg = colors.mauve, bold = true },
		TelescopePromptNormal = { bg = colors.surface0 },
		TelescopePromptPrefix = { bg = colors.surface0 },
		TelescopePromptTitle = { fg = colors.surface0, bg = colors.surface0 },
		TelescopeResultsBorder = { bg = colors.mantle, fg = colors.mantle },
		TelescopeResultsNormal = { bg = colors.mantle },
		TelescopeResultsTitle = { fg = colors.mantle, bg = colors.mantle },
		TelescopeSelection = { bg = colors.surface0 },
		VertSplit = { bg = "NONE", fg = colors.surface0 },
		WhichKeyFloat = { bg = colors.mantle },
		YankHighlight = { bg = colors.surface2 },
		FidgetTask = { fg = colors.subtext2 },
		FidgetTitle = { fg = colors.peach },
		IblIndent = { fg = colors.surface0 },
		IblScope = { fg = colors.overlay0 },
		-- Core Syntax Overrides
		Boolean = { fg = colors.mauve },
		Number = { fg = colors.mauve },
		Float = { fg = colors.mauve },
		PreProc = { fg = colors.mauve },
		PreCondit = { fg = colors.mauve },
		Include = { fg = colors.mauve },
		Define = { fg = colors.mauve },
		Conditional = { fg = colors.red },
		Repeat = { fg = colors.red },
		Keyword = { fg = colors.red },
		Typedef = { fg = colors.red },
		Exception = { fg = colors.red },
		Statement = { fg = colors.red },
		Error = { fg = colors.red },
		StorageClass = { fg = colors.peach },
		Tag = { fg = colors.peach },
		Label = { fg = colors.peach },
		Structure = { fg = colors.peach },
		Operator = { fg = colors.peach },
		Title = { fg = colors.peach },
		Special = { fg = colors.yellow },
		SpecialChar = { fg = colors.yellow },
		Type = { fg = colors.yellow, bold = true },
		Function = { fg = colors.green, bold = true },
		Delimiter = { fg = colors.subtext2 },
		Ignore = { fg = colors.subtext2 },
		Macro = { fg = colors.teal },
		-- Treesitter / LSP Links (Applying your specific mapping)
		["@annotation"] = { fg = colors.mauve },
		["@attribute"] = { fg = colors.mauve },
		["@boolean"] = { fg = colors.mauve },
		["@character"] = { fg = colors.teal },
		["@character.special"] = { link = "SpecialChar" },
		["@comment"] = { link = "Comment" },
		["@conditional"] = { fg = colors.red },
		["@constant"] = { fg = colors.text },
		["@constant.builtin"] = { fg = colors.mauve },
		["@constant.macro"] = { fg = colors.mauve },
		["@constructor"] = { fg = colors.green },
		["@debug"] = { link = "Debug" },
		["@define"] = { link = "Define" },
		["@error"] = { link = "Error" },
		["@exception"] = { fg = colors.red },
		["@field"] = { fg = colors.blue },
		["@float"] = { fg = colors.mauve },
		["@function"] = { fg = colors.green },
		["@function.builtin"] = { fg = colors.green },
		["@function.call"] = { fg = colors.green },
		["@function.macro"] = { fg = colors.green },
		["@include"] = { fg = colors.red },
		["@keyword"] = { fg = colors.red },
		["@keyword.function"] = { fg = colors.red },
		["@keyword.operator"] = { fg = colors.peach },
		["@keyword.return"] = { fg = colors.red },
		["@label"] = { fg = colors.peach },
		["@method"] = { fg = colors.green },
		["@method.call"] = { fg = colors.green },
		["@namespace"] = { fg = colors.yellow },
		["@none"] = { fg = colors.text },
		["@number"] = { fg = colors.mauve },
		["@operator"] = { fg = colors.peach },
		["@parameter"] = { fg = colors.text },
		["@parameter.reference"] = { fg = colors.text },
		["@preproc"] = { link = "PreProc" },
		["@property"] = { fg = colors.blue },
		["@punctuation.bracket"] = { fg = colors.text },
		["@punctuation.delimiter"] = { link = "Delimiter" },
		["@punctuation.special"] = { fg = colors.blue },
		["@repeat"] = { fg = colors.red },
		["@storageclass"] = { fg = colors.peach },
		["@storageclass.lifetime"] = { fg = colors.peach },
		["@strike"] = { fg = colors.subtext2 },
		["@string"] = { fg = colors.teal },
		["@string.escape"] = { fg = colors.green },
		["@string.regex"] = { fg = colors.green },
		["@string.special"] = { link = "SpecialChar" },
		["@symbol"] = { fg = colors.text },
		["@tag"] = { fg = colors.peach },
		["@tag.attribute"] = { fg = colors.green },
		["@tag.delimiter"] = { fg = colors.green },
		["@text"] = { fg = colors.green },
		["@text.danger"] = { link = "DiagnosticError" },
		["@text.diff.add"] = { link = "diffAdded" },
		["@text.diff.delete"] = { link = "diffRemoved" },
		["@text.emphasis"] = { italic = true },
		["@text.environment"] = { link = "Macro" },
		["@text.environment.name"] = { link = "Type" },
		["@text.literal"] = { link = "String" },
		["@text.math"] = { fg = colors.blue },
		["@text.note"] = { link = "DiagnosticInfo" },
		["@text.reference"] = { link = "Constant" },
		["@text.strike"] = { strikethrough = true },
		["@text.strong"] = { bold = true },
		["@text.title"] = { link = "Title" },
		["@text.todo"] = { link = "Todo" },
		["@text.underline"] = { underline = true },
		["@text.uri"] = { fg = colors.blue, underline = true },
		["@text.warning"] = { link = "DiagnosticWarn" },
		["@todo"] = { link = "Todo" },
		["@type"] = { fg = colors.yellow, bold = true },
		["@type.builtin"] = { fg = colors.yellow, bold = true },
		["@type.definition"] = { fg = colors.yellow, bold = true },
		["@type.qualifier"] = { fg = colors.peach, bold = true },
		["@uri"] = { fg = colors.blue },
		["@variable"] = { fg = colors.text },
		["@variable.builtin"] = { fg = colors.mauve },
		-- LSP Semantic Overrides
		["@lsp.type.class"] = { link = "@type" },
		["@lsp.type.comment"] = { link = "@comment" },
		["@lsp.type.decorator"] = { link = "@function" },
		["@lsp.type.enum"] = { link = "@type" },
		["@lsp.type.enumMember"] = { link = "@property" },
		["@lsp.type.events"] = { link = "@label" },
		["@lsp.type.function"] = { link = "@function" },
		["@lsp.type.interface"] = { link = "@type" },
		["@lsp.type.keyword"] = { link = "@keyword" },
		["@lsp.type.macro"] = { link = "@constant.macro" },
		["@lsp.type.method"] = { link = "@method" },
		["@lsp.type.modifier"] = { link = "@type.qualifier" },
		["@lsp.type.namespace"] = { link = "@namespace" },
		["@lsp.type.number"] = { link = "@number" },
		["@lsp.type.operator"] = { link = "@operator" },
		["@lsp.type.parameter"] = { link = "@parameter" },
		["@lsp.type.property"] = { link = "@property" },
		["@lsp.type.regexp"] = { link = "@string.regex" },
		["@lsp.type.string"] = { link = "@string" },
		["@lsp.type.struct"] = { link = "@type" },
		["@lsp.type.type"] = { link = "@type" },
		["@lsp.type.typeParameter"] = { link = "@type.definition" },
		["@lsp.type.variable"] = { link = "@variable" },
		-- Plugin specifics (Neotest, Coverage, Fzf)
		NeotestPassed = { fg = colors.green },
		NeotestFailed = { fg = colors.red },
		NeotestRunning = { fg = colors.yellow },
		NeotestSkipped = { fg = colors.blue },
		NeotestFile = { fg = colors.peach },
		NeotestNamespace = { fg = colors.peach },
		NeotestDir = { fg = colors.peach },
		NeotestFocused = { fg = colors.mauve, bold = true, underline = true },
		NeotestAdapterName = { fg = colors.red },
		NeotestIndent = { fg = colors.yellow },
		NeotestExpandMarker = { fg = colors.yellow },
		NeotestWinSelect = { fg = colors.yellow, bold = true },
		NeotestTest = { fg = colors.subtext2 },
		CoverageCovered = { fg = colors.green },
		CoverageUncovered = { fg = colors.red },
		FzfLuaNormal = { bg = colors.base },
		FzfLuaBorder = { fg = colors.base, bg = colors.base },
		FzfluaTitle = { fg = colors.text, bg = colors.overlay0, bold = true },
		FzfLuaTitleFlags = { fg = colors.text },
		FzfLuaBackdrop = { bg = colors.surface0 },
		FzfLuaPreviewNormal = { bg = colors.surface0 },
		FzfLuaPreviewBorder = { fg = colors.surface0, bg = colors.surface0 },
		FzfLuaPreviewTitle = { fg = colors.text, bg = colors.overlay0, bold = true },
		FzfLuaScrollBorderEmpty = { fg = colors.surface0, bg = colors.surface0 },
		FzfLuaScrollBorderFull = { fg = colors.subtext1, bg = colors.surface0 },
		FzfLuaScrollFloatEmpty = { fg = colors.surface0, bg = colors.surface0 },
		FzfLuaScrollFloatFull = { fg = colors.subtext1, bg = colors.surface0 },
		FzfLuaCursorLine = { bg = colors.surface2 },
		FzfLuaLivePrompt = { fg = colors.red },
	}

	for group, opts in pairs(highlights) do
		vim.api.nvim_set_hl(0, group, opts)
	end
end

vim.api.nvim_create_autocmd("ColorScheme", {
	group = vim.api.nvim_create_augroup("NativeCatppuccinOverrides", { clear = true }),
	pattern = "catppuccin*",
	callback = apply_custom_highlights,
})

vim.cmd("colorscheme catppuccin")
